// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC625CyK-CeB8JFgzJgxcIEJZ0PEbzFz4k',
    appId: '1:198786945858:web:fabeedbbba850b5e4d6edb',
    messagingSenderId: '198786945858',
    projectId: 'flutternoteapp-50e84',
    authDomain: 'flutternoteapp-50e84.firebaseapp.com',
    storageBucket: 'flutternoteapp-50e84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-eC9orqCmTijbcb0wLrWV4mZ13zt0W78',
    appId: '1:198786945858:android:9a086b83943d6f904d6edb',
    messagingSenderId: '198786945858',
    projectId: 'flutternoteapp-50e84',
    storageBucket: 'flutternoteapp-50e84.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC625CyK-CeB8JFgzJgxcIEJZ0PEbzFz4k',
    appId: '1:198786945858:web:9324ed9daa1cd57d4d6edb',
    messagingSenderId: '198786945858',
    projectId: 'flutternoteapp-50e84',
    authDomain: 'flutternoteapp-50e84.firebaseapp.com',
    storageBucket: 'flutternoteapp-50e84.firebasestorage.app',
  );
}
